config/routes.rb
Rails.application.routes.draw do
  get 'questions/answer', to: 'questions#answer'
  get 'questions/ask', to: 'questions#ask'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def answer
    if params[:query]
        @your_message = params[:query]
      if @your_message= "I am going to work right now!"
        @answer = ""
      elsif @your_message[-1] == "?"
        @answer = "Silly question, get dressed and go to work!"
      else
        @answer = "I don't care, get dressed and go to work!"
      end
    elsif params[:question]
      @your_message = params[:question]
      @answer = "Coach says hi!"
    end
  end

  def ask
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<p> <%= params[:question] %></p>
<p>-You</p>
<p><%= @answer %></p>
<p>-Coach</p>
<%= link_to "Click to ask another question", questions_ask_path %>

app/views/questions/ask.html.erb
<form action="/questions/answer">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="question" placeholder="what time is it?">
  <input type="submit" value="Go on!">
</form>
<p> <%= params[:query] %></p>
<h1><%= @answer %></h1>